# Generated by Django 4.2.5 on 2023-09-17 18:43

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0098_webhook_custom_field_data_webhook_tags'),
        ('netbox_acls', '0004_netbox_acls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aclextendedrule',
            name='destination_prefix',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\x08){4}/([0-9]|[1-2][0-9]|3[0-2])$', 'Only CIDR format allowed (x.x.x.x/y)')]),
        ),
        migrations.AlterField(
            model_name='aclextendedrule',
            name='source_prefix',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\x08){4}/([0-9]|[1-2][0-9]|3[0-2])$', 'Only CIDR format allowed (x.x.x.x/y)')]),
        ),
        migrations.AlterField(
            model_name='aclstandardrule',
            name='source_prefix',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^((25[0-5]|(2[0-4]|1\\d|[1-9]|)\\d)\\.?\x08){4}/([0-9]|[1-2][0-9]|3[0-2])$', 'Only CIDR format allowed (x.x.x.x/y)')]),
        ),
        migrations.CreateModel(
            name='FirewallRuleList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=500, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-_]+$', 'Only alphanumeric, hyphens, and underscores characters are allowed.')])),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('assigned_object_type', models.ForeignKey(limit_choices_to=models.Q(('app_label', 'dcim'), ('model', 'device_role')), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'Firewall Rule List',
                'verbose_name_plural': 'Firewall Rule Lists',
                'ordering': ['assigned_object_type', 'assigned_object_id', 'name'],
                'unique_together': {('assigned_object_type', 'assigned_object_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FWInterfaceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('assigned_object_id', models.PositiveBigIntegerField()),
                ('comments', models.TextField(blank=True)),
                ('assigned_object_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(models.Q(('app_label', 'dcim'), ('model', 'interface')), models.Q(('app_label', 'virtualization'), ('model', 'vminterface')), _connector='OR')), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('fw_rule_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_acls.firewallrulelist')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'FW Interface Assignment',
                'verbose_name_plural': 'FW Interface Assignments',
                'ordering': ['assigned_object_type', 'assigned_object_id', 'fw_rule_list', 'interface'],
                'unique_together': {('fw_rule_list', 'assigned_object_type', 'assigned_object_id')},
            },
        ),
        migrations.CreateModel(
            name='FWIngressRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('index', models.PositiveIntegerField()),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('destination_ports', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('protocol', models.CharField(blank=True, max_length=30)),
                ('source_prefix', models.CharField(blank=True, max_length=100)),
                ('fw_rule_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_acls.firewallrulelist')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'FW Ingress Rule',
                'verbose_name_plural': 'FW Ingress Rules',
                'ordering': ['fw_rule_list', 'index'],
                'abstract': False,
                'default_related_name': 'ingressrules',
                'unique_together': {('fw_rule_list', 'index')},
            },
        ),
        migrations.CreateModel(
            name='FWEgressRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('index', models.PositiveIntegerField()),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('destination_ports', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None)),
                ('protocol', models.CharField(blank=True, max_length=30)),
                ('destination_prefix', models.CharField(blank=True, max_length=100)),
                ('fw_rule_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='netbox_acls.firewallrulelist')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'FW Egress Rule',
                'verbose_name_plural': 'FW Egress Rules',
                'ordering': ['fw_rule_list', 'index'],
                'abstract': False,
                'default_related_name': 'egressrules',
                'unique_together': {('fw_rule_list', 'index')},
            },
        ),
    ]
