# Generated by Django 4.1.9 on 2023-06-23 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_acls", "0004_netbox_acls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ACLStandardRule",
            name="source_prefix",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}/([0-9]|[1-2][0-9]|3[0-2])$", "Only CIDR format allowed (x.x.x.x/y)"
                    )
                ],
            ),
        ),

        migrations.AlterField(
            model_name="ACLExtendedRule",
            name="source_prefix",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}/([0-9]|[1-2][0-9]|3[0-2])$", "Only CIDR format allowed (x.x.x.x/y)"
                    )
                ],
            ),
        ),

        migrations.AlterField(
            model_name="ACLExtendedRule",
            name="destination_prefix",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}/([0-9]|[1-2][0-9]|3[0-2])$", "Only CIDR format allowed (x.x.x.x/y)"
                    )
                ],
            ),
        ),
    ]
